### ISSUE TITLE
Remote Execution Not working

### ISSUE THREAD

**Issue by ErenBalatkan** [allegroai/clearml#378]
Example given on this readme file 
https://github.com/allegroai/clearml/blob/master/docs/clearml-task.md

Is resulting in an error. 

```
(base) computer@user:/path$ clearml-task --project keras_examples --name remote_test --repo https://github.com/allegroai/events.git --script /webinar-0620/keras_mnist.py --args batch_size=64 epochs=1 --queue default
ClearML launch - launch any codebase on remote machine running clearml-agent

Error: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by jkhenning** [comment]
Hi @ErenBalatkan, which ClearML SDK version are you using?

**Comment by jkhenning** [comment]
@ErenBalatkan this was fixed in the master branch, and will be released soon - you can try installing directly from the repository to make sure it works for you:
`pip install git+https://github.com/allegroai/clearml.git`

**Comment by ErenBalatkan** [comment]
Hello, I was using ClearML 1.0.3 installed form pip

I installed from Github as you suggested, current version is `1.0.4rc0`
Still getting the same error on call
```
clearml-task --project keras_examples --name remote_test --repo https://github.com/allegroai/events.git --script /webinar-0620/keras_mnist.py --args batch_size=64 epochs=1 --queue default
```

**Comment by bmartinn** [comment]
Hi @ErenBalatkan 

Should work now, RC will be released soon :)
```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by ErenBalatkan** [comment]
Thanks for the quıick update, now it works!
