### ISSUE TITLE
Only part of the tensorboard logging is tracked

### ISSUE THREAD

**Issue by ddebby** [allegroai/clearml#527]
I have run a long term experiments with clearml, using the auto-track methods to track tensorboard logs.
Only the first few epochs' logs are tracked, while ohters are missing.

Some of the packages version as follows:

clearml                           1.1.4
clearml-agent                     1.1.1
clearml-serving                   0.3.3
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0

**Comment by jkhenning** [comment]
Hi @ddebby ,

Can you share some more regarding your actual code? What exactly are you training, and how/when are you calling `Task.init()`?

**Comment by ddebby** [comment]
> 

I have pushed my sample code here: https://github.com/ddebby/debug_clearml
The entry scritps is here: `/projects/test.py` . It's a tutorial code from MMdetection: [Source code is here](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb). I only modified it to work in clearml.
P.S.: MMdetection is a tool based on pytorch.

I have the following experiments results:

1. Train from my local machine and just tracking in clearm-server: everything is ok;
2. Train on a clearml-agent resources with docker env, always stuck in `waiting to finish uploads` before task.close(). And this is an infinite stuck;
3. Close all the `auto_connect_frameworks`, still stuck in `waiting to finish uploads`.

**Comment by ddebby** [comment]
I use clearml-session run scripts in a remote jupyter, the stuck of ouputs in this jupyter is as follows(Epochs 4):
![training](https://user-images.githubusercontent.com/7961354/147718104-64985d7a-9226-4942-85dc-0180698030dd.jpg)
Console log from clearml server is few epochs before(Epochs 3):
![console](https://user-images.githubusercontent.com/7961354/147718147-55a11c31-330b-4204-a8a7-97e37a5b15fb.PNG)

**Comment by jkhenning** [comment]
Hi @ddebby ,

Can you try with the latest clearml 1.1.5rc7?

**Comment by ddebby** [comment]
> 

Thank you @jkhenning. This issue seems fixed with  the latest clearml 1.1.5rc7. I'll do more tests. Also hope the new version of clearml releases soon.

**Comment by jkhenning** [comment]
Well, as it so happens, we've just released it last night 🙂 (see https://github.com/allegroai/clearml/releases)

**Comment by ddebby** [comment]
> Well, as it so happens, we've just released it last night 🙂 (see https://github.com/allegroai/clearml/releases)

As I do more tests with the new version of clearml, this issue still occur and stuck in a middle proccess as mention above.

**Comment by jkhenning** [comment]
Hi @ddebby,

Since then we've released a few more fixes related to subprocess handling - can you please check with the latest version (1.1.6rc0)?

**Comment by ddebby** [comment]
> Hi @ddebby,
> 
> Since then we've released a few more fixes related to subprocess handling - can you please check with the latest version (1.1.6rc0)?

Sure, I'll try and collect more experiments logs.

**Comment by ddebby** [comment]
> 

This issue is fixed with the new 1.1.7 version.

**Comment by bmartinn** [comment]
Thanks @ddebby 
Closing this issue, please reopen if the problem consists.
