### ISSUE TITLE
Unnecessary "Welcome to ClearML" popup

### ISSUE THREAD

**Issue by daniel-bogdoll** [allegroai/clearml#537]
Hello everybody,

while the "WELCOME TO CLEARML" message is indeed great for the first visit, it becomes unnecessary right after the local setup and first use. Using the website a lot, it even becomes quite annoying :D Could there be a way to disable this popup? Even a simple On/Off Toggle in the settings without any logic would make me happy :)

Version: 1.1.1-135 • 1.1.1 • 2.14

![image](https://user-images.githubusercontent.com/19552411/149341500-2296d879-854f-439a-90e4-d92937cf50e0.png)

**Comment by jkhenning** [comment]
Hi @daniel-bogdoll,

Are you using a self-deployed server?

**Comment by daniel-bogdoll** [comment]
Hi, yes! Sorry, I forgot to mention that.

**Comment by daniel-bogdoll** [comment]
No, nothing like that. A colleague of mine has the same issue.

**Comment by shyallegro** [comment]
thanks, we'll investigate

**Comment by tienduccao** [comment]
I also have the same issue

**Comment by DerekChia** [comment]
Same issue for me, very annoying.

**Comment by shyallegro** [comment]
Hi @DerekChia @tienduccao ,
we're trying to verify this issue was indeed solved for 1.2 before the release.
can you please describe how ClearML is installed in your environment (e.g. local docker, VM on AWS, behind some speciel routing) and how are you accessing it (which browser, VPN, IP+port or some internal address)

thanks,
Shy

**Comment by DerekChia** [comment]
I'm using ClearML with the docker compose installation, and putting it behind docker-swag (https://github.com/linuxserver/docker-swag) through Nginx reverse proxy.

**Comment by DerekChia** [comment]
Hello, is there any update to this issue?

**Comment by shayh** [comment]
Hi,
We've just released 1.2, although we weren't able to reproduce, we've tried to make sure it didn't happen.
we'll appreciate any feedback

**Comment by shyallegro** [comment]
Hi,
We've just released 1.2, although we weren't able to reproduce, we've tried to make sure it didn't happen.
we'll appreciate any feedback

**Comment by DerekChia** [comment]
Thanks, I will try out 1.2 once available and check if problem persists.
